# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    verify-gradle-wrapper:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
            - uses: gradle/actions/wrapper-validation@16bf8bc8fe830fa669c3c9f914d3eb147c629707 # v4

    build:
        if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                jdk: [17, 21]
        steps:
            - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
            - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
              with:
                path: |
                    ~/.gradle/caches
                    ~/.gradle/wrapper
                key: ${{ runner.os }}-jdk-${{ matrix.jdk }}-gradlewrapper-${{ hashFiles('**/gradle-wrapper.properties') }}-gradlescripts-${{ hashFiles('**/*.gradle*') }}
                restore-keys: |
                    ${{ runner.os }}-jdk-${{ matrix.jdk }}-gradlewrapper-${{ hashFiles('**/gradle-wrapper.properties') }}-gradlescripts-
            - name: Set up JDK
              uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
              with:
                  distribution: 'adopt'
                  java-version: ${{ matrix.jdk }}
            - run: chmod +x gradlew
            - run: ./gradlew build --stacktrace --warning-mode all

    release:
        runs-on: ubuntu-latest
        needs: [build, verify-gradle-wrapper] # build job must pass before we can release

        if: github.event_name == 'push'
            && github.ref == 'refs/heads/main'
            && github.repository == 'MinimallyCorrect/DefaultsPlugin'
            && !contains(toJSON(github.event.commits.*.message), '[skip release]')

        steps:
            - name: Check out code
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
              with:
                  fetch-depth: '0' # https://github.com/shipkit/shipkit-changelog#fetch-depth-on-ci

            - name: Set up Java 11
              uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
              with:
                  distribution: 'adopt'
                  java-version: 17

            - name: Build and publish to github
              run: ./gradlew -P releasing publish publishPlugins githubRelease -s
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  GRADLE_PUBLISH_KEY: ${{secrets.GRADLE_PUBLISH_KEY}}
                  GRADLE_PUBLISH_SECRET: ${{secrets.GRADLE_PUBLISH_SECRET}}
                  DEPLOYMENT_REPO_URL_RELEASE: ${{secrets.DEPLOYMENT_REPO_URL_RELEASE}}
                  DEPLOYMENT_REPO_URL_SNAPSHOT: ${{secrets.DEPLOYMENT_REPO_URL_SNAPSHOT}}
                  DEPLOYMENT_REPO_USERNAME: ${{secrets.DEPLOYMENT_REPO_USERNAME}}
                  DEPLOYMENT_REPO_PASSWORD: ${{secrets.DEPLOYMENT_REPO_PASSWORD}}
